# Generated by Django 4.0.3 on 2022-04-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='Приватность'),
        ),
    ]
