# Generated by Django 4.0.3 on 2022-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_photo_isprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='Приватность'),
        ),
    ]
