# Generated by Django 4.0.3 on 2022-04-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_album_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
